#!/usr/bin/env node
var lisp = require('./index.js'),
    optimist = require('optimist'),
    argv = optimist.argv;

if (argv._.length > 0) {
    console.log(lisp.loadFile(argv._[0]));
} else {
    var buf = '';
    process.stdin.resume();
    process.stdin.setEncoding('utf-8');
    process.stdin.on('data', function (s) {
        buf += s;
    });
    process.stdin.on('end', function (s) {
        console.log(lisp.evaluate(buf));
    });
}
